// Code generated by raiden-cli; DO NOT EDIT.
package bootstrap

import (
	"github.com/sev-2/raiden"
	raiden_controllers "github.com/sev-2/raiden/pkg/controllers"
	"github.com/valyala/fasthttp"
	rest_v1_doctors "medpoint/internal/controllers/rest/v1/doctors"
	rest_v1_facilities "medpoint/internal/controllers/rest/v1/facilities"
	rest_v1_notifications "medpoint/internal/controllers/rest/v1/notifications"
	rest_v1_payments "medpoint/internal/controllers/rest/v1/payments"
	rest_v1_reservations "medpoint/internal/controllers/rest/v1/reservations"
	rest_v1_schedules "medpoint/internal/controllers/rest/v1/schedules"
	rest_v1_services "medpoint/internal/controllers/rest/v1/services"
	rest_v1_users "medpoint/internal/controllers/rest/v1/users"
	"medpoint/internal/models"
)

func RegisterRoute(server *raiden.Server) {
	server.RegisterRoute([]*raiden.Route{
		raiden.NewRouteFromController(&raiden_controllers.StateReadyController{}, []string{fasthttp.MethodPost}),
		{
			Type:       raiden.RouteTypeRest,
			Path:       "/rest/v1/doctors",
			Methods:    []string{},
			Controller: &rest_v1_doctors.RestController{},
			Model:      models.Doctors{},
		},
		{
			Type:       raiden.RouteTypeRest,
			Path:       "/rest/v1/facilities",
			Methods:    []string{},
			Controller: &rest_v1_facilities.RestController{},
			Model:      models.Facilities{},
		},
		{
			Type:       raiden.RouteTypeRest,
			Path:       "/rest/v1/notifications",
			Methods:    []string{},
			Controller: &rest_v1_notifications.RestController{},
			Model:      models.Notifications{},
		},
		{
			Type:       raiden.RouteTypeRest,
			Path:       "/rest/v1/payments",
			Methods:    []string{},
			Controller: &rest_v1_payments.RestController{},
			Model:      models.Payments{},
		},
		{
			Type:       raiden.RouteTypeRest,
			Path:       "/rest/v1/reservations",
			Methods:    []string{},
			Controller: &rest_v1_reservations.RestController{},
			Model:      models.Reservations{},
		},
		{
			Type:       raiden.RouteTypeRest,
			Path:       "/rest/v1/schedules",
			Methods:    []string{},
			Controller: &rest_v1_schedules.RestController{},
			Model:      models.Schedules{},
		},
		{
			Type:       raiden.RouteTypeRest,
			Path:       "/rest/v1/services",
			Methods:    []string{},
			Controller: &rest_v1_services.RestController{},
			Model:      models.Services{},
		},
		{
			Type:       raiden.RouteTypeRest,
			Path:       "/rest/v1/users",
			Methods:    []string{},
			Controller: &rest_v1_users.RestController{},
			Model:      models.Users{},
		},
	})
}
