// Code generated by raiden-cli; DO NOT EDIT.
package bootstrap

import (
	"github.com/sev-2/raiden/pkg/resource"
	"medpoint/internal/types"
)

func RegisterTypes() {
	resource.RegisterTypes(
		&types.Doctors{},
		&types.Facilities{},
		&types.Notifications{},
		&types.Payments{},
		&types.Reservations{},
		&types.Schedules{},
		&types.Services{},
		&types.UserRole{},
		&types.Users{},
	)
}
