// Code generated by raiden-cli; DO NOT EDIT.
package Payments

import (
	"github.com/sev-2/raiden"
	"medpoint/internal/models"
)

type RestController struct {
	raiden.ControllerBase
	Model models.Payments
}
